<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师管理",
			            "menuJump":"列表",
			            "tableName":"jiaoshi"
			        }
			    ],
			    "menu":"教师管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"用户管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"用户管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"打卡记录管理",
                        "menuJump":"列表",
                        "tableName":"dakajilu"
                    }
                ],
                "menu":"打卡记录管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"学生申请通行证管理",
                        "menuJump":"列表",
                        "tableName":"shenhetongxingzheng"
                    }
                ],
                "menu":"学生申请通行证"
            }
           
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"通行证管理",
                        "menuJump":"列表",
                        "tableName":"tongxingzheng"
                    }
                ],
                "menu":"通行证管理"
            }

			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"留言信息管理",
			            "menuJump":"列表",
			            "tableName":"liuyanxinxi"
			        }
			    ],
			    "menu":"留言信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
				],
			    "menu":"公告类型管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	       {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"打卡记录管理",
	                    "menuJump":"列表",
	                    "tableName":"dakajilu"
	                }
	            ],
	            "menu":"打卡记录管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核",
	                        "删除"
	                    ],
	                    "menu":"学生申请通行证管理",
	                    "menuJump":"列表",
	                    "tableName":"shenhetongxingzheng"
	                }
	            ],
	            "menu":"学生申请通行证"
	        }
	       
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"通行证管理",
	                    "menuJump":"列表",
	                    "tableName":"tongxingzheng"
	                }
	            ],
	            "menu":"通行证管理"
	        }
	
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "修改"
			            ],
			            "menu":"留言信息管理",
			            "menuJump":"列表",
			            "tableName":"liuyanxinxi"
			        }
			    ],
			    "menu":"留言信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	}
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"打卡记录管理",
	                    "menuJump":"列表",
	                    "tableName":"dakajilu"
	                }
	            ],
	            "menu":"打卡记录管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"学生申请通行证管理",
	                    "menuJump":"列表",
	                    "tableName":"shenhetongxingzheng"
	                }
	            ],
	            "menu":"学生申请通行证"
	        }
	       
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"通行证管理",
	                    "menuJump":"列表",
	                    "tableName":"tongxingzheng"
	                }
	            ],
	            "menu":"通行证管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除"
			            ],
			            "menu":"留言信息管理",
			            "menuJump":"列表",
			            "tableName":"liuyanxinxi"
			        }
			    ],
			    "menu":"留言信息管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
